# Generated by Django 3.1 on 2020-10-20 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Stations', '0001_initial'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='branch_station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField()),
                ('KM', models.FloatField()),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_station', to='branches.branch')),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stations.stations')),
            ],
            options={
                'db_table': 'branch_station',
                'unique_together': {('branch_id', 'idx')},
            },
        ),
    ]
