# Generated by Django 3.1 on 2020-10-20 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('governorate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idS', models.IntegerField(unique=True)),
                ('operationCode', models.IntegerField(unique=True)),
                ('name', models.JSONField()),
                ('IsActive', models.BooleanField(default=0)),
                ('governorate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Gov_id', to='governorate.governorate')),
            ],
            options={
                'db_table': 'stations',
            },
        ),
    ]
